### ISSUE TITLE
[Q] How do I add a custom CPU target to quickstart.py?

### ISSUE THREAD

**Issue by reikdas** [microsoft/Accera#60]
### What's your question?
How do I add a custom CPU target to the `quickstart.py` example?

### Include context on what you are trying to achieve
If I try to run `quickstart.py`, I get the warning:
```
Warning: Your host machine "AMD Ryzen Threadripper PRO 7965WX 24-Cores" is not a known target model. To generate optimal code, we recommend that you inspect the accera.Target.Models enumeration to find the closest matching target model,
and create a Target using that model. You may also define a custom target if there is no closest match.
For more details please refer to this link: https://microsoft.github.io/Accera/Reference/classes/Target/Target/#known-device-names
```
Therefore, I tried to add details of my own CPU as a target with `cpu_target = acc.Target(name="Custom processor", category=acc.Target.Category.CPU, architecture=acc.Target.Architecture.X86_64, num_cores=24, extensions=["SSE4.1", "SSE4.2", "AVX2", "AVX512"], runtime="OPENMP")`
and set it as the target with `plan = schedule.create_plan(cpu_target)`.

Now I get the error:
```
Traceback (most recent call last):
  File "/local/scratch/a/das160/accera-tests/quickstart.py", line 38, in <module>
    package.add(plan, args=(A, B, C), base_name="matmul_relu_fusion_transformed")
  File "/local/scratch/a/das160/.local/lib/python3.10/site-packages/accera/Package.py", line 259, in add
    return self._add_function(source, args, base_name, parameters, function_opts, auxiliary)
  File "/local/scratch/a/das160/.local/lib/python3.10/site-packages/accera/Package.py", line 387, in _add_function
    validate_target(source.target)
  File "/local/scratch/a/das160/.local/lib/python3.10/site-packages/accera/Package.py", line 306, in validate_target
    raise NotImplementedError(
NotImplementedError: Function target being added is currently incompatible with existing functions in package
```

Should I be adding the target in a different way?

#### Context details

 - OS and version (e.g. Ubuntu 20.04): macOS 15.1
 - Python version (e.g. 3.7): 3.10.15
 - Accera version/# commit (for example, the output of `pip show accera`): 1.2.29

### Include details of what you already did to find answers
I have tried removing/changing config options from my custom target, but it always resulted in the same error.

**Comment by lisaong** [comment]
Currently, packages don't support mixed targets (the documentation had missed this, apologies).

You can try creating a new package for your cpu_target and build it, like this:

```python
cpu_target = acc.Target(name="Custom processor", category=acc.Target.Category.CPU, architecture=acc.Target.Architecture.X86_64, 
                    vector_bytes=32, vector_registers=16,
                    extensions=["SSE4.1", "SSE4.2", "AVX2", "AVX512"])

cpu_package = acc.Package()
cpu_plan = schedule.create_plan(cpu_target) 
cpu_package.add(cpu_plan, args=(A, B, C), base_name="matmul_relu_fusion_transformed")
print(cpu_package.build(name="hello_accera", format=acc.Package.Format.HAT_DYNAMIC))
```

The warning will still remain though, since it is using a static lookup table, but the build should now use your custom target's config.
